travis:
  secure:
    BINSTAR_TOKEN: KoNvIvQXc6jU0hak0CPBj9KGnmFak0G52/QOjrGaEBHFm+fRTA3iP4TrgV/rs89unxjqaHFu9z99w5c8lQL70GxjkhiazKtUUpNrYc0DMqTbkHRzTm4TB9Elpy5+JxnanFpez26PQ1spKH4GJtwKCMiQL3LrvU6a/8nd55q0ZgaNndoeZInyiLEeXYO+Y9gEVmI0ogEE3kGw3HGa6QUSteSOqTUO0KJ2HiD1B2cbHf1XFypQ9TjdmzYOuvP2xZPkznpf2SvgoZAT3GKkOzWpQu0Bdej7G9Kv24S9L5T7JyW/jTd8hA8Oj6PyeG20d0PsKWCWubm1amexSa9lE/rpr6wqinwqtRp0vsb3MlIVd3kyl0l0PGq86Q+jBFvGtTxeJARu5+DiNqFmITWetTuK2hpepMFcr9vxRX8xbdY8RqgD8BXWGl+D1fO+MFPbrCoJ3Vb/lHzUTV8cvjvZzSxHw+d+8FLtdCRZ7zqNz/otHhDtR+/smb8kYbOmfdUsmRAO6yEuunqI9NnRQia1VahL7nRCVKp/yArF0vHlNAFWZN9DQBrMpEm5LCXOqP1oGEHVCrPgsJ3XVcGM2EiDz5EeEJD7yfSxpaO6ig3RXVYKM/zU17jQ72g4QSssXA8FEhR1jxrhB/oJ0pTs+6W04EtoAmwbD7qYFVX9BYrJTlnuKNA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
